# Generated by Django 3.1.6 on 2021-02-16 03:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kennywoodapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_occupancy', models.IntegerField(null=True)),
                ('height_requirement_inches', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'attraction',
                'verbose_name_plural': 'attractions',
            },
        ),
        migrations.CreateModel(
            name='AttractionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='TargetPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'population',
                'verbose_name_plural': 'populations',
            },
        ),
        migrations.CreateModel(
            name='ParkArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('target_population', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kennywoodapi.targetpopulation')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
            },
        ),
        migrations.CreateModel(
            name='AttractionRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('note', models.TextField(max_length=500, null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kennywoodapi.attraction')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', to='kennywoodapi.visitor')),
            ],
            options={
                'verbose_name': 'rating',
                'verbose_name_plural': 'ratings',
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attractions', to='kennywoodapi.parkarea'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attractions', to='kennywoodapi.attractioncategory'),
        ),
    ]
